services:
  trippster:
    image: postgres:14-alpine
    container_name: trippster
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=db_trippster
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - 5435:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local